# Project information
site_name: Crystaleum-2
site_url: https://github.com/mdsreq-fga-unb/2024.1-Crystaleum

# Repository
repo_name: mdsreq-fga-unb/2024.1-Crystaleum-2
repo_url: https://github.com/mdsreq-fga-unb/2024.1-Crystaleum-2

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Page tree
nav:
  - Home: index.md
