# Project information
site_name: Crystaleum-2
site_url: https://github.com/mdsreq-fga-unb/2024.1-Crystaleum-2

# Repository
repo_name: mdsreq-fga-unb/2024.1-Crystaleum-2
repo_url: https://github.com/mdsreq-fga-unb/2024.1-Crystaleum-2

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  features:
    - navigation.tabs

# Page tree
nav:
  - Nossa história: index.md
  - Visão Geral do Produto:
      - Posição do Produto: visao-produto/posicao-produto.md
      - Problema: visao-produto/problema.md

  - Acompanhamento:
      - Atas: 
        - Ata de Reunião 1: acompanhamento/atas/ata1.md
      - Relatórios: 
        - Relatório 1: acompanhamento/relatorios/relatorio1.md
  
  - Visão Geral do Projeto:
      - Organização do Projeto: visao-projeto/organizacao-projeto.md

  - Processo de Desenvolvimento de Software: processo-desenvolvimento/index.md
  
  - Missão 1: 
      - Material do Seminário: missao1/materiais-seminario/processos.md
      - Lições Aprendidas: missao1/licoes-aprendidas/licao.md
      - Apresentação: missao1/apresentacao/apresentacao1.md
  - Missão 2: 
      - Backlog: missao2/backlog.md
      - Apresentação: missao2/apresentacao.md
  - Missão 3:
      - PBB: missao3/pbb.md
      - USM: missao3/usm.md
  - Missão 4:
      - Correções Missão 3:
        - PBB Corrigido: missao4/correcoes-missao3/pbb.md
        # - USM: missao4/correcoes-missao3.md
  
